### PR TITLE
ServiceBinding and ServiceConfigurator

### PR DESCRIPTION
**Pull request by JakenVeina**
Implemented ServiceBinding and ServiceConfigurator for proposal #738.

Implemented proper usage of these for all DI-registered services in Modix.Common.

### CODE REVIEW

**Comment by Inzanit** [comment]
Hadn't seen this yet - apologies.

I can see the problem you're trying to solve, although I'm personally not entirely sold on this solution. I think the components/modules that register the necessary types could be cleaned up and the rest would sort itself out.

I'm not a particular fan of putting a custom layer on top, which we might have to end up changing if MS IoC changes etc. Keeping it vanilla, and standardizing/cleaning up registration might be a better shout here.

**Comment by JakenVeina** [comment]
I don't see Microsoft making significant changes to DI as at all likely. If they did, we can refactor.

I see this as basically the same idea as how `ModelBuilder` decentralization works in Modix.Data. Yeah, we can clean up the DI methods a bit, but that still puts DI setup for a class in a totally separate location than the class itself, and makes it easy to screw it up. And there isn't really any good way to test DI setups. Even if you could fully validate the DI system, that still doesn't mean it's correct.

**Comment by Scott-Caldwell** [comment]
Just had a thought. With [Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) becoming a thing, could we possibly get the best of both worlds here? I haven't looked too deeply into what Source Generators are capable of yet, but it seems to me that we could make a Source Generator that looked for attributes and generated calls to Microsoft's standard IoC APIs based on that.

So based on the current attributes in the PR, maybe something like
```cs
[ServiceBinding(ServiceLifetime.Scoped)]
public class MessagePublisher : IMessagePublisher
```
could produce something like
```cs
services.AddScoped<IMessagePublisher, MessagePublisher>();
```
in the body of a generated method that we call when configuring our services.

Admittedly, part of my motivation here is just me thinking it'd be cool to play around with Source Generators.

**Comment by JakenVeina** [comment]
That is an eventual possibility, but it wouldn't be something we could embed directly into our solution. Someone would have to implement and publish this as a separate NuGet package. It's basically the equivalent of an Analyzer, from what I can tell.

**Pull request merged**
