### PR TITLE
Add stocks module

### PR DESCRIPTION
**Pull request by mariocatch**
Got bored, requires an API key (free, and I can supply one if needed).

Sample output:

```
Trade information for: [goog]
04:00 PM    Open: $1051.01    Close: $1053.91    High: $1054.82    Low: $1050.45    Volume: 204427
03:00 PM    Open: $1052.94    Close: $1052.07    High: $1056.71    Low: $1048.80    Volume: 69051
02:00 PM    Open: $1051.22    Close: $1052.52    High: $1055.80    Low: $1051.22    Volume: 42687
01:00 PM    Open: $1051.98    Close: $1051.30    High: $1053.90    Low: $1049.37    Volume: 52829
12:00 PM    Open: $1047.68    Close: $1051.94    High: $1056.50    Low: $1047.67    Volume: 78473
11:00 AM    Open: $1052.57    Close: $1047.82    High: $1053.26    Low: $1047.15    Volume: 126573
10:00 AM    Open: $1058.54    Close: $1052.93    High: $1060.55    Low: $1050.51    Volume: 156675

Summary for [goog]
---------------
- opened at: $1058.54
- closed at: $1053.91
- growth: $-4.63
- highest: $1060.55
- lowest: $1047.15
---------------

Market hasn't opened yet today - showing yesterday's results
```

### CODE REVIEW

**Comment by Cisien** [comment]
I'll do a full review if we decide to accept this feature, but as it sits, i dont see the value that this brings to our community. We have taken similar changes in the past which went unmaintained, and were eventually dropped.

**Comment by mariocatch** [comment]
@Cisien agreed - couldn't sleep last night so here we are. I also added the stackoverflow, wiki, and bet modules in the past (at least one of which I think hasn't been updated and has issues), so it's understandable.

This is trustie btw.

**Comment by jrusbatch** [comment]
I agree with Cisien - it's a neat feature but I don't think it would see much use. 

@Cisien Any reason to leave this open?

**Comment by Cisien** [comment]
closing since nobody voiced favor for this feature

**Pull request closed without merging**
