### PR TITLE
Fixes #274: Removed Abstained from Promotion Approval Percentage

### LINKED ISSUE #274: Promotions approval percentage
Should the calculated approval percentage for campaigns be `Approved / (Approved + Abstained + Opposed)` or `Approved / (Approved + Opposed)`? I noticed that the `!promotions` command includes abstains in the total, but the progress bar on the web page doesn't. Which is the preferred method?

### PR DESCRIPTION
**Pull request by Sutarodo**
Ignored comments abstaining from promotion approval/opposition from percentage.

### CODE REVIEW

**Comment by Sutarodo** [comment]
> We should probably check that `totalVotes` isn't zero before dividing in `GetApprovalPercentage`. Edge case for sure, but worth accounting for.

Will default it to use `totalApprovals` if that's the case so it will turn into 100% in the `PromotionsModule`.

**Comment by calledude** [comment]
> 
> 
> We should probably check that `totalVotes` isn't zero before dividing in `GetApprovalPercentage`. Edge case for sure, but worth accounting for.

Is it even physically possible for it to be 0 _ever_? Seeing as the one making the promotion in the first place has no option but to approve, right?

**Comment by Scott-Caldwell** [comment]
The campaign creator has the option to edit their sentiment to abstain if they want

**Comment by Sutarodo** [comment]
Therefore if there is not even an approval rating, we can just return 0, to be multiplied into 0%.

**Pull request merged**
