### PR TITLE
Improved exit function on disconnect

### PR DESCRIPTION
**Pull request by calledude**
Hopefully improves how the program behaves if/when we need to exit.

I am a strong advocate for nuking things when it goes to shit, hence the `Environment.Exit(-1)`. Let's hope it'll never come to that, however.

### CODE REVIEW

**Comment by jrusbatch** [comment]
`Environment.Exit(-1)` will tear down the website, too. Is there a way to try reconnecting instead of exiting?

**Comment by jmazouri** [comment]
> `Environment.Exit(-1)` will tear down the website, too. Is there a way to try reconnecting instead of exiting?

We probably don't need to worry about that - the frontend is basically useless without the bot running anyway, and we can rely on Nginx for a nice static page when the server is down if we want.

**Comment by jrusbatch** [comment]
Looks like this needs rebased.

**Comment by calledude** [comment]
> Looks like this needs rebased.

Fixed

> `Environment.Exit(-1)` will tear down the website, too. Is there a way to try reconnecting instead of exiting?

The only case where that code executes is if everything has gone to shit and the program is basically in an unrecoverable state anyway. Currently our bot (including the website) shuts down whenever the bot disconnects, even for a second, so it's not like this will make it any worse.

With that said, I don't really understand why we're doing it this way in the first place. I feel like any time I ask why we won't use the reconnection functionality of d.net all I get for answers are "it's easier" but no actual reason why that is.

**Pull request closed without merging**
