### PR TITLE
Allow for reason when unbanning

### PR DESCRIPTION
**Pull request by spixy**
https://github.com/discord-csharp/MODiX/issues/579

### CODE REVIEW

**Comment by JakenVeina** [comment]
So, this is just for the sake of forwarding the reason to Discord? We're not storing it in our DB?

**Comment by spixy** [comment]
or better to `ModerationActionEntity`?

**Comment by JakenVeina** [comment]
The moderations data model could maybe use a refactor, in general, but no, I think it makes more sense on `InfractionEntity` for the time being, if only because that's where `Reason` and `RescindActionId` are.

**Comment by Inzanit** [comment]
Left enhancement for storing in databse in #579

**Pull request merged**
