### PR TITLE
Add a bomb command for the mass conversion of a guild to Inzanit kind 

### PR DESCRIPTION
**Pull request by Perksey**
Need I say more?

### CODE REVIEW

**Comment by Jay-Madden** [comment]
i cant imagine a scenario where this isnt useful

**Comment by kameko** [comment]
finally, modix is useful

**Comment by Inzanit** [comment]
After closely reviewing this PR, unfortunately we cannot accept this contribution at this time, because we feel the codebase isn't quite ready for such a substantial change. We will keep this on the backlog and revisit once the time is right!

**Comment by Perksey** [comment]
That's all I ask! :D

**Comment by john-h-k** [comment]
Seems critical to get this in system ASAP

**Comment by Perksey** [comment]
@john-h-k I agree, the Inzanit Bomb is the easiest solution to an out of control server.

**Pull request closed without merging**
