### PR TITLE
Ignore commands from bots and webhooks

### PR DESCRIPTION
**Pull request by Scott-Caldwell**

### CODE REVIEW

**Comment by JakenVeina** [comment]
Nonono, definitely don't build the context there, that's gonna cause exceptions (I think) when it attempts to parse a command out of a message that doesn't have one.

Check against `message.Author`.

**Comment by Scott-Caldwell** [comment]
Sorry! Still getting used to the codebase.

**Comment by JakenVeina** [comment]
Not a problem at all.

Any chance you can clean up that commit history now? I can walk you through the process, if you'd like.

**Comment by JakenVeina** [comment]
Actually, this is probably a perfectly fine opportunity for whoever merges it to just do a squash merge.

**Pull request merged**
