### PR TITLE
Add (click here) text to starboard and quote embeds

### LINKED ISSUE #749: Consider making the jump link in Message links more visible
On my server there has been a lot of confusion about how to actually jump to a linked conversation. I propose that we somehow make it clear that this is a hyper link.
image

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
Resolves #749.

image

image

### CODE REVIEW

**Comment by Inzanit** [comment]
As a point, do you not think it might be an idea to standardize where we show the jump link?

As you can see in the quote, it's in the footer area, while on the starboard, it's the first thing seen. I would think it's useful to have it in the same spot - that being the footer. Contextually - I would be more interested in seeing the actual message in Starboard first, rather than where it was posted.

Just a suggestion.

**Comment by Jay-Madden** [comment]
note: this also closes #749

**Comment by Scott-Caldwell** [comment]
> note: this also closes #749

Yup, that's why I put "Resolves #749." in my original message, so that GitHub would automatically close that issue out when this is merged

**Comment by Scott-Caldwell** [comment]
> As a point, do you not think it might be an idea to standardize where we show the jump link?
> 
> As you can see in the quote, it's in the footer area, while on the starboard, it's the first thing seen. I would think it's useful to have it in the same spot - that being the footer. Contextually - I would be more interested in seeing the actual message in Starboard first, rather than where it was posted.
> 
> Just a suggestion.

Makes sense to me. Updated so that the starboard embed matches the quote embed.

**Comment by Jay-Madden** [comment]
> Yup, that's why I put "Resolves #749." in my original message, so that GitHub would automatically close that issue out when this is merged

oops i missed that lol

**Pull request merged**
