### PR TITLE
Add !clean command

### LINKED ISSUE #27: Cleaning-Module to clean up messy discussions(a.k.a deleting)

### LINKED ISSUE #168: Proposal: Implement !cleanup <#OfMessages> command
This command could be used for cleaning/deleting a large number of messages in a channel.

Usage: !cleanup 5
Result: Deletes the last 5 messages in the channel the command is executed in.

Usage: !cleanup 5 channelID/channelName
Result: Same thing, but with the option to pick channels

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
Closes #27.
Closes #168.

Adds a `!clean [#] ([channel] | [user])?` command.
* If a channel is supplied, deletes `#` messages in that channel.
* If a channel is not supplied, deletes `# + 1` messages in the channel where the command was posted. (`# + 1` to cleanup `#` messages plus the command message itself.)

Requires the new `ModerationMassDeleteMessages` claim.

Currently has an upper limit of 100 messages.

Filtering options (e.g. only delete bot messages, only delete unranked messages, etc.) were considered, but I decided against them for this initial PR. We can add options for those later if we feel like they'd be useful.

image

image

### CODE REVIEW

**Comment by Scott-Caldwell** [comment]
Currently it follows the same pattern as the other message deletion services (e.g. attachment purging) and logs each message that was deleted. Do you think that suffices, or do we need to look for a better solution?

It *is* understandably a little messy right now...

image

**Comment by JakenVeina** [comment]
We could probably enahnce the `DeletedMessageRepository` to support deleting many messages at once, and thus be able to publish a single `DeletedMessagesCreatedNotification` for all of them, rather than one individual notification for each message. In this case, I don't think there's any need to include each individual message within #mod-log, but we should definitely add a UI for perusing the history of deleted messages, in general. Then, we can just have the #mod-log entry.

On a separate note, if this doesn't already, this command ABSOLUTELY needs to have a confirmation "dialog".

**Comment by Scott-Caldwell** [comment]
Update: added the confirmation dialog and batch table. Working on the web interface for viewing deleted messages now.

image

**Comment by Scott-Caldwell** [comment]
I think I've got everything updated now. Ready for another review

cc: @JakenVeina

**Comment by Scott-Caldwell** [comment]
@jmazouri Resolved

**Comment by jrusbatch** [comment]
@Scott-Caldwell This needs rebased

**Comment by Scott-Caldwell** [comment]
Should be resolved now

**Pull request merged**
