### PR TITLE
Add !wrongchannel command

### PR DESCRIPTION
**Pull request by Sergio0694**
Added a new `!wrongchannel` command to help with the never ending issue we have in `#lowlevel` 🤣

### Syntax

`!wrongchannel <USER_ID>`

### Output

>  Hey `@SomeUserInTheWrongChannel`! 👋
> You'll want to ask in another channel, such as `#help-0`. This channel, as per the description, is for:
>> "Low level programming discussion around the very intricate implementation details of the C# language, the speeds, quirks and optimisations"
>
> Lowlevel in this context refers to being "close to hardware" or about more advanced hardware details in general.
> Thank you!

### CODE REVIEW

**Comment by Perksey** [comment]
Shouldn't this be a tag?

**Comment by Sergio0694** [comment]
@Perksey Used a command instead of a tag so we can have the embed also tag the target user for a greeting, which means the whole message feel more personal and less like you're just getting an automated response 🙂

**Comment by n-Ultima** [comment]
IMO this can just be a tag. Mainly, instead of wanting a greeting, we can add functionality for if a tag is called, and if the calling message is referencing another message, MODiX can simply reply to the referenced message with the tag's content.

**Comment by sylveon** [comment]
> so we can have the embed also tag the target user for a greeting, which means the whole message feel more personal and less like you're just getting an automated response 🙂

The tag system should instead be improved to support these kinds of things.

**Comment by n-Ultima** [comment]
Well, we really can't put embeds inside of a tag, because the "!tag create <TagName> <Content>" takes strings. Default users on Discord can't generate embeds, so the whole embed idea won't work.

**Comment by Cisien** [comment]
We could let the tag creator post the embed json format somehow, or create them in the web ui

**Comment by patrickklaeren** [comment]
MODiX is multi tenanted - or at least that is the intention - this doesn't lend itself to a dedicated command unfortunately.

I think out of this it's evident that the tag system should be able to create an embed response for a tag. Which could be done by us implementing a rudimentary "custom" syntax for them. I.e. `<embed>Hello world</embed>` or simply saying the whole tag response should be rendered as an embed. Plenty of options here.

**Comment by Scott-Caldwell** [comment]
It seems like the consensus here is that this should probably be a tag, and that tag functionality should be enhanced to allow embeds (whatever form that takes). I would tend to agree, this is far too specific to be a separate command.

**Pull request closed without merging**
