### PR TITLE
Updated markdown-discord to fix XSS.

### PR DESCRIPTION
**Pull request by Kuinox**
markdown-discord is not updated and lead to an xss:
image

Beware: it's 4AM and I only copy pasted the new version from the github web interface, I didn't tested anything.

### CODE REVIEW

**Review by Scott-Caldwell — CHANGES_REQUESTED** [review]
(Just copying the contents of the updated file does not work)

```
vue.runtime.esm.js:1888 TypeError: r(...) is not a function
    at u (Util.ts:61)
    at o.parseDiscordContent (ModixComponent.vue?902a:17)
    at o.get markdownPreview (TagCreationModal.vue?be5d:113)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)
    at o.markdownPreview (vue.runtime.esm.js:4836)
    at o.h (TagCreationModal.vue?7806:1)
    at o.Sn.e._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    ```

**Comment by Kuinox** [comment]
I can't say I didn't expected something like this.

**Comment by Cisien** [comment]
any reason to keep copying contents instead of replacing this file with the actual npm package?

**Comment by Scott-Caldwell** [comment]
We'll want to evaluate the right way to do this - we might just be best off using the package itself like Cisien mentioned.

**Comment by Kuinox** [comment]
image

**Pull request closed without merging**
