### PR TITLE
Add infraction modify command

### LINKED ISSUE #155: Proposal: Ability to change infraction severity
Pretty self explanatory. Add the ability to change the severity of any infraction. We have the ability to change the comment on an infraction. Being able to change the rank of an infraction would compliment this. This also works well with #74 and #66 too.

image

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
Fixes #155.

This PR adds a number of new commands under the `!infraction` group:
- `!infraction modify note`
- `!infraction modify warn`
- `!infraction modify mute`
- `!infraction modify tempmute`
- `!infraction modify ban`
- `!infraction modify forceban`

Each of the above commands takes an infraction ID. The `tempmute` variant requires a duration, similar to the existing `!tempmute` command. The reason is an optional parameter for all variants. If it is supplied, then the modified infraction is saved with the supplied reason. If it is not supplied, then the modified infraction retains the comment from the existing infraction.

image

### CODE REVIEW

**Comment by JakenVeina** [comment]
I'm honestly not a fan of these new commands. Given how much push-back we've gotten recently about non-obvious commands, I'm hesitant to add any new Discord frontend commands that aren't being asked for, don't have an immediate avantage, or don't have trivial parameters.

The ability to modify infractions (I.E. delete and replace them, so history is maintained in the ModerationActions table) seems like something we should restrict to just the Web UI.

If so, what we can do is implement a single-infraction details page, which allows mods and/or the original author to edit/replace them, and we can provide a link to this page, with the attached infraction ID, from #mod-log.

**Comment by Scott-Caldwell** [comment]
That's fair. Now that you mention it, the web UI does seem like a much cleaner interface for something like this. I can look into it.

**Comment by JakenVeina** [comment]
Sorry. I'm also not a fan of work getting thrown away. In the future, if you wanna pick up an issue, leave a comment on it, that way if there's any dicussion about it that needs to happen, it can happen before you put a bunch of effort into it.

Also, you could join the MODiX-Dev Discord Guild.

**Comment by Scott-Caldwell** [comment]
No worries, I'm doing this for fun, and to get myself acclimated with the repository. I don't count anything here as loss.

Do you have an invite link for that guild? For the life of me I can't find it anywhere

**Pull request closed without merging**
