### PR TITLE
Introduce a "drunk module"

### PR DESCRIPTION
**Pull request by john-h-k**
clearly needed after the perksey fiasco yesterday. he was too strong to be stopped

### CODE REVIEW

**Comment by Perksey** [comment]
Is this really enough though? Will anything ever be enough?

**Comment by john-h-k** [comment]
it can only help

**Comment by Cisien** [comment]
This looks like it's a joke, if it's serious, then it needs some work, and to remove the list of hard-coded drunks.

Also, why doesn't the existing moderation features cover this?

**Comment by john-h-k** [comment]
> then it needs some work, and to remove the list of hard-coded drunks.

I have never used D# or Discord.NET before so was really guessing my way around. The harcoded drunks was just because I have no idea the correct way to do it

> This looks like it's a joke, if it's serious

It is a joke to an extent, but given you can't mute users in void chat, could legitimately be useful

> Also, why doesn't the existing moderation features cover this?

I considered adding it to `ModerationModule` but thought it wasn't serious enough for that

**Comment by Cisien** [comment]
the void chat channel isn't moderated because unrelated features can cause messages to 'leak' from there. (starboard, quote, links, etc).

Work should be done to put those behind proper permissions, and to allow moderation features to work server-wide.

**Comment by Scott-Caldwell** [comment]
> (starboard, quote, links, etc)
To be fair, I'm pretty sure anyone can quote from #void-chat etc. already. Last time we had a conversation about quoting private channels, I think we just landed on saying that if you're trusted enough to be in the channel, you're trusted enough to know what's safe to leak and what isn't.

For starboard, we have an `IgnoredFromStarboard` channel designation that as far as I know works correctly, and it looks like #void-chat already has that designation. So if that's the only thing keeping #void-chat `Unmoderated`, it's probably safe to make it moderated.

**Comment by 333fred** [comment]
> To be fair, I'm pretty sure anyone can quote from #void-chat etc. already.

Yep. As an example: https://discordapp.com/channels/143867839282020352/175609431478894594/586352133784207380

**Comment by Inzanit** [comment]
Due to legal issues, any mention of Inzanit must be first cleared with Inzanit's legal team, which is unavailable currently. Please book an appointment via Discord and we can discuss legalities and royalties.

**Pull request closed without merging**
