### PR TITLE
Infraction Restore Command

### PR DESCRIPTION
**Pull request by QuesosNachos**
New PR for infraction restore command

### CODE REVIEW

**Comment by QuesosNachos** [comment]
Needs to be tested

**Comment by QuesosNachos** [comment]
It appears that restoring an infraction throws this error message, stating that warning type infractions cannot be rescinded. 

https://paste.mod.gg/ajujoyewov.json

**Comment by Scott-Caldwell** [comment]
>It appears that restoring an infraction throws this error message, stating that warning type infractions cannot be rescinded.
>
>https://paste.mod.gg/ajujoyewov.json

I suspect that's because you're explicitly setting the duration to Zero. Duration is nullable in the database, so it's fine to leave null if we don't want Modix to try to auto-rescind the infraction.

If it's a mute, we could get fancy and try to calculate how long the original infraction has left before it would have expired, or we could just leave it null there too - that'll just impose the constraint that if you want to restore a mute and have it actually take effect, the moderator will just have to create a new infraction.

(This PR assumes that restoring an infraction would just add the restored infraction record without trying to reapply the effects of the infraction e.g. for mutes and bans.)

**Comment by Scott-Caldwell** [comment]
Now that I'm thinking about it, I'm wondering if we'd want to copy the rescind action from the original infraction as well if there is one... Would we ever be in a situation where someone accidentally deletes a rescinded mute or ban and wants to restore the infraction without applying the effects?

**Comment by QuesosNachos** [comment]
I can change it to null then. We could check the original infraction duration for mutes and bans and then reapply those if we want.

I see this command as more of a "shortcut" to restoring an infraction we may have deleted by accident. I would like to figure out a system that is more explicit in stating that this infraction was restored and isn't technically new.

**Comment by Scott-Caldwell** [comment]
Now that I think about it even more, I'm pretty sure we do want to copy the rescind action as well if there is one on the original, at least if the infraction is a mute. Otherwise, if the user leaves and rejoins, Modix will see that they have an unrescinded, undeleted mute on their profile and thence give the user the mute role, even if the original mute had expired.

Definitely an edge case, so we could probably put it on the backlog for the future if it's too much trouble for now. The workaround/mitigation is obviously just to `!unmute` the user in the rare case where this scenario would come up.

**Comment by Inzanit** [comment]
Closing out for now, can be revisited once all cases are discussed.

**Pull request closed without merging**
